/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const mangel_Logic = require('./code/mangel-logic');

class accessPageSrv extends LCAPApplicationService {
    async init() {

        this.on(['CREATE', 'READ', 'UPDATE'], 'Mangel', async (request, next) => {
            return mangel_Logic(request, next);
        });

        return super.init();
    }
}


module.exports = {
    accessPageSrv
};